"use client"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { UrgencyBadge } from "@/components/shared/UrgencyBadge"
import { EmptyState } from "@/components/shared/EmptyState"
import { LoadingSkeleton, CardSkeleton } from "@/components/shared/LoadingSkeleton"
import { useQuery } from "@tanstack/react-query"
import { analysisApi } from "@/lib/api/analysis"
import {
  Sparkles,
  AlertCircle,
  BookOpen,
  Scale,
  CheckCircle2,
  RefreshCw,
} from "lucide-react"
import { formatDate } from "@/lib/utils/date"

interface CaseAnalysisProps {
  caseId: string
}

export function CaseAnalysis({ caseId }: CaseAnalysisProps) {
  const { data: analysis, isLoading, refetch } = useQuery({
    queryKey: ["ai-analysis", caseId],
    queryFn: () => analysisApi.getAnalysis(caseId),
  })

  if (isLoading) {
    return (
      <div className="space-y-6">
        <CardSkeleton />
        <CardSkeleton />
      </div>
    )
  }

  if (!analysis || analysis.status === "pending") {
    return (
      <Card>
        <CardContent className="pt-6">
          <EmptyState
            icon={<Sparkles className="h-8 w-8 text-slate-400" />}
            title="AI analysis not available"
            message="This case hasn't been analyzed yet. Trigger an analysis to get AI-powered insights."
            action={
              <Button onClick={() => refetch()}>
                <Sparkles className="mr-2 h-4 w-4" />
                Analyze Case
              </Button>
            }
          />
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="space-y-6">
      {/* Analysis Header */}
      <Card className="bg-gradient-to-br from-indigo-50 to-purple-50 border-indigo-200">
        <CardContent className="pt-6">
          <div className="flex items-start justify-between">
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-lg bg-indigo-100">
                <Sparkles className="h-5 w-5 text-indigo-600" />
              </div>
              <div>
                <h3 className="font-bold text-slate-900 mb-1">
                  AI Case Analysis
                </h3>
                <p className="text-sm text-slate-600">
                  Generated by Claude 3.5 Sonnet •{" "}
                  {analysis.processed_at &&
                    formatDate(analysis.processed_at, "PPP")}
                </p>
              </div>
            </div>
            <Button variant="outline" size="sm" onClick={() => refetch()}>
              <RefreshCw className="mr-2 h-4 w-4" />
              Refresh
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Case Summary */}
      <Card>
        <CardHeader>
          <CardTitle>Case Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-slate-700 leading-relaxed">
            {analysis.case_summary}
          </p>
        </CardContent>
      </Card>

      {/* Priority & Deadlines */}
      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-amber-600" />
              Priority Level
            </CardTitle>
          </CardHeader>
          <CardContent>
            <UrgencyBadge level={analysis.urgency_level!} />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-red-600" />
              Upcoming Deadlines
            </CardTitle>
          </CardHeader>
          <CardContent>
            {analysis.analysis.deadline_reminders.length > 0 ? (
              <div className="space-y-3">
                {analysis.analysis.deadline_reminders.map((reminder, i) => (
                  <div
                    key={i}
                    className="rounded-lg border border-slate-200 p-3"
                  >
                    <div className="flex items-start justify-between mb-1">
                      <h4 className="font-bold text-slate-900 text-sm">
                        {reminder.task}
                      </h4>
                      <Badge
                        variant={
                          reminder.priority === "critical"
                            ? "destructive"
                            : "warning"
                        }
                        className="text-xs"
                      >
                        {reminder.priority}
                      </Badge>
                    </div>
                    <p className="text-xs text-slate-600">
                      Due: {formatDate(reminder.due_date, "PPP")}
                    </p>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-600">No deadlines identified</p>
            )}
          </CardContent>
        </Card>
      </div>

      {/* Key Legal Issues */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Scale className="h-5 w-5 text-indigo-600" />
            Key Legal Issues
          </CardTitle>
        </CardHeader>
        <CardContent>
          <ul className="space-y-2">
            {analysis.analysis.key_legal_issues.map((issue, i) => (
              <li key={i} className="flex items-start gap-2">
                <CheckCircle2 className="h-5 w-5 text-emerald-600 flex-shrink-0 mt-0.5" />
                <span className="text-slate-700">{issue}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      {/* Relevant Statutes */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <BookOpen className="h-5 w-5 text-indigo-600" />
            Relevant Statutes
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {analysis.analysis.relevant_statutes.map((statute, i) => (
              <Badge key={i} variant="outline">
                {statute}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Precedent Cases */}
      {analysis.analysis.precedent_cases.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Relevant Precedents</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {analysis.analysis.precedent_cases.map((precedent, i) => (
                <div
                  key={i}
                  className="border-l-4 border-indigo-600 pl-4 py-2"
                >
                  <h4 className="font-bold text-slate-900 mb-1">
                    {precedent.name}
                  </h4>
                  <p className="text-sm text-slate-600 mb-2">
                    {precedent.citation}
                  </p>
                  <p className="text-sm text-slate-700">
                    {precedent.relevance}
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Action Items */}
      {analysis.analysis.action_items.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Recommended Actions</CardTitle>
          </CardHeader>
          <CardContent>
            <ol className="space-y-2 list-decimal list-inside">
              {analysis.analysis.action_items.map((item, i) => (
                <li key={i} className="text-slate-700">
                  {item}
                </li>
              ))}
            </ol>
          </CardContent>
        </Card>
      )}
    </div>
  )
}